added zoom-window

diff --git a/bin/mousetree b/bin/mousetree
--- a/bin/mousetree
+++ b/bin/mousetree
@@ -32,7 +32,7 @@ fi
 #
 
 state_f="/tmp/mousetree-$USER"
-state_rx='([0-9]+) ([0-9]+) ([0-9]+) ([0-9]+)'
+state_rx='(-?[0-9]+) (-?[0-9]+) (-?[0-9]+) (-?[0-9]+)'
 
 state_parse() {
 	if [[ $1 =~ $state_rx ]]; then
@@ -77,6 +77,26 @@ move() {
 	xdotool mousemove $1 $2
 }
 
+zoom() {
+	state_fromx=$(($x - $w))
+	state_fromy=$(($y - $h))
+	state_tox=$(($x + $w))
+	state_toy=$(($y + $h))
+}
+
+zoom_win_rx='Position: (-?[0-9]+),(-?[0-9]+).*Geometry: (-?[0-9]+)x(-?[0-9]+)'
+zoom_win() {
+	if [[ $(xdotool getwindowgeometry "$1") =~ $zoom_win_rx ]]; then
+		state_fromx=${BASH_REMATCH[1]}
+		state_fromy=${BASH_REMATCH[2]}
+		staet_tox=$(($state_fromx + ${BASH_REMATCH[3]}))
+		state_toy=$(($state_fromy + ${BASH_REMATCH[4]}))
+	else
+		echo "Invalid window geometry."
+		exit 1
+	fi
+}
+
 #
 ## Interface
 #
@@ -110,8 +130,14 @@ elif [ "$1" = left ]; then
 elif [ "$1" = right ]; then
 	state_fromx=$x
 	move $(avg $x $state_tox) $y
+elif [ "$1" = "zoom-cursor" ]; then
+	[ "$2" = "" ] && w=400 || w="$2"
+	[ "$3" = "" ] && h=400 || h="$3"
+	zoom $w $h
+elif [ "$1" = "zoom-window" ]; then
+	zoom_win "$(xdotool getactivewindow)"
 else
-	echo "Usage: $0 <up|down|left|right|reset|reset-state>"
+	echo "Usage: $0 <up|down|left|right|reset|reset-state|zoom-cursor|zoom-window>"
 	exit 1
 fi
 
